#!/bin/bash
herbstclient --idle 'kill_hooks|tag_changed.*' | while read -r; do
		  if [ "$REPLY" == "kill_hooks" ]; then
								echo "last_tag hook closing!"
												exit $?
														  fi
																	  cat $HLWM_PATH/.current_tag > $HLWM_PATH/.last_tag
																				  echo "$REPLY" | cut -f2 > $HLWM_PATH/.current_tag
																						 done
