#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
	    herbstclient "$@"
}

#hc emit_hook reload

hc set window_gap 5

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class~'[Ss]talonetray' manage=off

#autostart
$HOME/.config/herbstluftwm/wsbar.sh
#stalonetray &
#add padding for dzen2
hc pad 0 16 0 0 0

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-q quit
#hc keybind $Mod-n reload
hc keybind $Mod-c close

# Applications
hc keybind $Mod-Shift-r spawn dmenu_run
hc keybind $Mod-Shift-Return spawn urxvt 
hc keybind $Mod-Shift-w spawn chromium

# tags
TAG_NAMES=( "Eins" "Zwei" "Drei" "Vier" "Fünf" "Sechs" "Sieben" )
TAG_KEYS=( {1..7} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
	    hc add "${TAG_NAMES[$i]}"
			    key="${TAG_KEYS[$i]}"
					    if ! [ -z "$key" ] ; then
								        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
												        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
																    fi
																		done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-m set_layout max 
hc keybind $Mod-v set_layout vertical
hc keybind $Mod-h set_layout horizontal
hc keybind $Mod-Control-v split vertical 0.5
hc keybind $Mod-Control-h split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-j cycle 1
hc keybind $Mod-k cycle -1

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

# colors
hc set frame_border_active_color '#1793D0'
hc set frame_border_normal_color '#123456'
hc set frame_bg_transparent 1
hc set frame_border_width 1
hc set window_border_width 1
hc set window_border_normal_color '#123456'
hc set window_border_active_color '#1793D0'
